-- MySQL Workbench Synchronization
-- Generated: 2017-09-28 13:30
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: shepherd

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

ALTER TABLE `weiqiumi`.`users` 
CHANGE COLUMN `name` `nickname` VARCHAR(100) NULL DEFAULT NULL COMMENT '微信昵称' ,
ADD COLUMN `gender` INT(11) NULL DEFAULT NULL COMMENT '性别' AFTER `nickname`,
ADD COLUMN `city` VARCHAR(100) NULL DEFAULT NULL COMMENT '城市' AFTER `gender`,
ADD COLUMN `province` VARCHAR(100) NULL DEFAULT NULL COMMENT '省份' AFTER `city`,
ADD COLUMN `avatarurl` VARCHAR(1000) NULL DEFAULT NULL COMMENT '头像地址' AFTER `province`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
